### ISSUE TITLE
Question on Ghostboard’s check-link feature

### ISSUE THREAD

**Issue by hiensarahly** [ghostboard/check-link#1]
Hi, first of all please excuse me opening an issue here, I wanted to ask a question about Ghostboard. But haven’t found the admin contact information anywhere.

I hope you won’t mind. 

Wanted to ask: Does Ghostboard show where the links are broken, meaning on which posts. And can we fix it live right on the Ghostboard dashboard?

Thanks!

**Comment by dburgos** [comment]
Hi @hiensarahly no problem, also you can [tweet us](https://twitter.com/TryGhostboard) or find the contact email on the Terms & Conditions web page. 

On other hand, if you are a Ghostboard user, inside your dashboard there is a Support section with several ways to contact including a direct form.

About your questions:
- Yes, you can find each page where is the broken link. Find an example below
- No, to fix it you need to enter your Ghost Admin, then edit the post/page containing the broken link and update it.

<img width="1210" alt="Captura de Pantalla 2022-06-26 a las 16 08 45" src="https://user-images.githubusercontent.com/1589874/175818177-0a37864b-0f5d-4bbe-b1cc-cbc10aa9dac7.png">


Yeah I think it would be helpful to see a counter, will plan to add it

Thanks for your message! :)
